humanRel/apps/sysmanager/urls.py
from django.urls import path, re_path
from apps.sysmanager import views

urlpatterns = [
    re_path('register$', views.register, name="register"),
    re_path('login/', views.login, name="login"),
    re_path('logout', views.logout, name="logout"),
    re_path('index$', views.index, name="index"),
    re_path('set$', views.set, name="set"),
    re_path('check_code$', views.check_code, name="check_code"),
]

humanRel/humanRel/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sys/', include(("apps.sysmanager.urls", "app-sys"), namespace="app-sys")),
    path('base/', include(("apps.baseinfo.urls", "app-base"), namespace="app-base")),
    path('busi/', include(("apps.business.urls", "app-busi"), namespace="app-busi")),
    path('rep/', include(("apps.report.urls", "app-rep"), namespace="app-rep")),
]

humanRel/apps/sysmanager/models.py
from django.db import models

# Create your models here.


class Parameters(models.Model):
    user = models.ForeignKey(verbose_name="用户", to="sysmanager.User", related_name="parametersUser", null=True, on_delete=models.PROTECT)
    code = models.CharField(verbose_name="代码", max_length=50)
    name = models.CharField(verbose_name="名称", max_length=50)
    pClass = models.IntegerField(verbose_name="分类", choices=((1, "系统"), (2, "资料"), (3, "往来"), (4, "报表"), (99, "其他")))
    sValue = models.CharField(verbose_name="参数值", max_length=255)
    remark = models.CharField(verbose_name="备注", max_length=255, null=True)


class User(models.Model):
    name = models.CharField(verbose_name="用户名", max_length=50)
    person = models.ForeignKey(verbose_name="人员", to="baseinfo.Person", related_name="userPerson", null=True, on_delete=models.SET_NULL)
    mobile = models.CharField(verbose_name="手机号码", max_length=20, null=True)
    email = models.CharField(verbose_name="电子邮箱", max_length=50, null=True)
    loginPW = models.CharField(verbose_name="登录密码", max_length=50)
    status = models.IntegerField(verbose_name="状态", choices=((0, "失效"), (1, "正常"), (2, "冻结")), default=1)

    def __str__(self):
        return self.name

humanRel/apps/sysmanager/views.py
from django.shortcuts import render, HttpResponse, redirect, reverse
from apps.sysmanager.models import User
from apps.baseinfo.models import Person
from django.forms import Form, fields, widgets
from django import forms
import json

# Create your views here.


class FormUser(Form):
    name = fields.CharField(
        label="用户名",
        min_length=6,
        max_length=20,
        widget=widgets.TextInput(attrs={"class": "regType"}),
        error_messages={
            "min_length": "用户名长度不能小于6",
            "max_length": "用户名长度不能大于20"
        }
    )
    person = forms.ModelChoiceField(
        label="人员",
        widget=widgets.Select(attrs={"class": "inputType"}),
        queryset=Person.objects.all()
    )
    mobile = fields.CharField(
        label="手机号码",
        min_length=11,
        max_length=11,
        widget=widgets.TextInput(attrs={"class": "regType"}),
        error_messages={
            "min_length": "手机号码长度不能小于11",
            "max_length": "手机号码长度不能大于11"
        }
    )
    email = fields.EmailField(
        label="电子邮箱",
        required=False,
        widget=widgets.EmailInput(attrs={"class": "regType"})
    )
    loginPW = fields.CharField(
        label="登录密码",
        widget=widgets.PasswordInput(attrs={"class": "regType"})
    )
    reloginPW = fields.CharField(
        label="确认登录密码",
        widget=widgets.PasswordInput(attrs={"class": "regType"})
    )


def register(request):
    if request.method == "GET":
        obj = FormUser()
        return render(request, "sysmanager/register.html", {"form": obj})
    elif request.method == "POST":
        obj = FormUser(request.POST)
        loginPW = request.POST.get("password", None)
        reloginPW = request.POST.get("repassword", None)
        if loginPW != reloginPW:
            return render(request, "sysmanager/register.html", {"form": obj, "info": "两次输入的密码不同"})
        res = obj.is_valid()
        if res:
            obj.cleaned_data.pop("reloginPW")
            User.objects.create(**obj.cleaned_data)
            return redirect(reverse("app-sys:index"))
        else:
            return render(request, "sysmanager/register.html", {"form": obj})


def login(request):
    if request.method == "GET":
        return render(request, "sysmanager/login.html", {"info": ""})
    elif request.method == "POST":
        checkcode = request.POST.get("checkcode", None)
        if not checkcode:
            return render(request, "sysmanager/login.html", {"info": "请输入验证码"})
        if checkcode.upper() != request.session["CheckCode"].upper():
            return render(request, "sysmanager/login.html", {"info": "验证码错误"})
        username = request.POST.get("username", None)
        userpw = request.POST.get("userpw", None)
        if not username:
            return render(request, "sysmanager/login.html", {"info": "请输入用户名"})
        rec = User.objects.filter(name=username).first()
        if not rec:
            return render(request, "sysmanager/login.html", {"info": "用户名无效"})
        sPW = rec.loginPW
        if not sPW:
            sPW = ""
        if userpw != sPW:
            return render(request, "sysmanager/login.html", {"info": "密码错误"})
        request.session.set_expiry(36000)
        request.session["LoginUser"] = username
        return redirect(reverse("app-sys:index"))
    else:
        return HttpResponse("无效的请求方式：%s" % (request.method))


def logout(request):
    rtn = {
        "result": False,
        "data": None,
        "info": None
    }
    try:
        del request.session["LoginUser"]
        rtn["result"] = True
    except Exception as e:
        pass
    return HttpResponse(json.dumps(rtn))


def auth(func):
    def inner(request, *args, **kwargs):
        userName = request.session.get("LoginUser", None)
        if not userName:
            return redirect(reverse("app-sys:login"))
        user = User.objects.filter(name=userName).first()
        if not user:
            return redirect(reverse("app-sys:login"))
        return func(request, user.id, *args, **kwargs)
    return inner


@auth
def index(request, userID):
    if request.method == "GET":
        return render(request, "sysmanager/index.html")


@auth
def set(request, userID):
    if request.method == "GET":
        rec = User.objects.filter(id=userID).first()
        dic = {
            "id": rec.id,
            "person": rec.person
        }
        obj = FormUser(initial=dic)
        return render(request, "sysmanager/set.html", {"form": obj, "userID": userID})
    elif request.method == "POST":
        obj = FormUser(request.POST)
        res = obj.is_valid()
        if res:
            obj.changed_data.pop("id")
            User.objects.filter(id=userID).update(**obj.cleaned_data)
            return redirect(reverse("app-sys:index"))
        else:
            return render(request, "sysmanager/set.html", {"form": obj, "userID": userID})


def check_code(request):
    """
    返回验证码图片
    :param request:
    :return:
    """
    from io import BytesIO
    from utils.check_code import create_validate_code
    img, code = create_validate_code((148, 40))
    stream = BytesIO()
    img.save(stream, 'PNG')
    request.session["CheckCode"] = code
    return HttpResponse(stream.getvalue())

humanRel/templates/sysmanager/index.html
{% extends "../extends/frameMain.html" %}


{% block pageTitle %}首页{% endblock %}


{% block styleFrame %}
    <style>
        .lanTitle{
            font-size: 32px;
            color: rgb(167, 167, 167);
            margin: 30px 0;
        }
        .lanItem{
            font-size: 18px;
            color: rgb(167, 167, 167);
            margin: 20px 0 0 0;
        }
    </style>
{% endblock %}


{% block contentsFrame %}
    <div style="padding: 80px 10px 10px 70px; ">
        <p><div class="lanTitle">古人云</div></p>
        <p><span class="lanItem">世情薄，人情恶，雨送黄昏花易落。—— 南宋才女,陆游表妹 唐琬 《钗头凤》。</span></p>
        <p><span class="lanItem">天下熙熙，皆为利来；天下壤壤，皆为利往。—— 西汉史学家,思想家,文学家 司马迁 《史记·货殖列传》。</span></p>
        <p><span class="lanItem">人情淡薄，世态炎凉，只喜添锦上之花，谁肯送雪中之炭！—— 明末清初文学家、戏曲家 李渔《意中缘传奇》。</span></p>
        <p><span class="lanItem">人情似纸张张薄，世事如棋局局新。贫居闹市无人问，富在深山有远亲。</span></p>
        <p><span class="lanItem">不信但看宴中酒，杯杯先敬富贵人。门前拴上高头马，不是亲来也是亲。</span></p>
        <p><span class="lanItem">门前放根讨饭棍，亲戚故友不上门。世人结交需黄金，黄金不多交不深。</span></p>
        <p><span class="lanItem">酒肉朋友朝朝有，无钱无势亲不亲。相逢好比初相识，到老终无怨恨心。</span></p>
        <p><span class="lanItem">近水楼台先得月，向阳花木易为春。谁人背后无人说，那个人前不说人。</span></p>
        <p><span class="lanItem">如若十分都使尽，远在儿孙近在身。长江后浪推前浪，世上新人赶旧人。</span></p>
        <p><span class="lanItem">岂无远道思亲泪，不及高堂念子心。堂上二老是活佛，何用灵山朝世尊。</span></p>
        <p><span class="lanItem">富贵若从奸狡起，世间呆汉喝西风。求人须求大丈夫，济人须济急时无。</span></p>
    </div>
{% endblock %}

humanRel/templates/sysmanager/login.html
{% extends "../extends/frame.html" %}


{% block styleMain %}
    <style>
        #inputUser, #inputPwd{
            border: rgb(221, 221, 221) 1px solid;
            border-radius: 4px;
            width: 280px;
            height: 40px;
            padding-left: 38px;
            font-size: 14px;
        }
        #inputCheck{
            display: inline-block;
            border: #DDDDDD 1px solid;
            border-radius: 4px;
            width: 112px;
            height: 40px;
            font-size: 14px;
            padding-left: 38px;
            vertical-align: top;
        }
        #imgCheck{
            display: inline-block;
            border: #DDDDDD 1px solid;
            border-radius: 4px;
            width: 150px;
            height: 42px;
            font-size: 14px;
            margin-left: 10px;
            vertical-align: top;
        }
        #btnLogin{
            border: none;
            background-color: rgb(17, 150, 219);
            border-radius: 4px;
            width: 318px;
            height: 42px;
            font-size: 16px;
            color: white;
        }
        a{
            font-size: 12px;
        }
    </style>
{% endblock %}

{% block contentsMain %}
    <div style="margin-top: 200px; "></div>
    <div style="width: 320px; padding: 0 80px; margin: 10px auto; ">
        {% include "../include/relFlag.html" %}
    </div>
    <div style="height: 320px; background-color: #F9F9F9; ">
        <div style="width: 320px; height: 320px; padding: 0 80px; margin: 0 auto; background-color: #F2F2F2; overflow: hidden; ">
            <form action="{% url 'app-sys:login' %}" method="POST">
                {% csrf_token %}
                <div></div>
                <div style="width: 320px; margin-top: 40px; position: relative; ">
                    <input id="inputUser" type="text" name="username" placeholder="请输入用户名" />
                    <div style="display: inline-block; width: 24px; height: 24px; background-image: url('/static/images/login.png'); background-position-y: 0; position: absolute; left: 10px; top: 10px;"></div>
                </div>
                <div style="width: 320px; margin-top: 20px; position: relative; ">
                    <input id="inputPwd" type="password" name="userpw" placeholder="请输入密码" />
                    <div style="display: inline-block; width: 24px; height: 24px; background-image: url('/static/images/login.png'); background-position-y: -24px; position: absolute; left: 10px; top: 10px;"></div>
                </div>
                <div style="display: inline-block; margin-top: 20px; ">
                    <input id="inputCheck" type="text" name="checkcode" placeholder="请输入验证码" />
                </div>
                <div style="display: inline-block;margin-top: 20px;  ">
                    <img id="imgCheck" src="{% url 'app-sys:check_code' %}">
                </div>
                <label class="promptInfo">{{ info }}</label>
                <div style="width: 320px; margin-top: 20px; ">
                    <input id="btnLogin" type="submit" value="登录" />
                </div>
            </form>
        </div>
    </div>
    <div>
        <div style="width: 320px; padding: 0 80px; margin: 0 auto; ">
            <p><a href="{% url 'app-sys:register' %}">注册新用户</a></p>
            <p><a href="">忘记密码？</a></p>
        </div>
    </div>
    <script src="/static/js/jquery3.4.1.js"></script>
    <script>
        $("#imgCheck").click(function () {
            $(this).attr("src", $(this).attr("src") + "?");
        });
    </script>
{% endblock %}

humanRel/templates/sysmanager/register.html
{% extends "../extends/frame.html" %}


{% block styleMain %}
    <style>
        .regType{
            font-size: 16px;
            width: 250px;
            height: 35px;
            margin-top: 3px;
            border: rgb(221, 221, 221) 1px solid;
            border-radius: 4px;
        }
        .regOther{
            font-size: 16px;
            margin-top: 10px;
        }
        .regButton{
            font-size: 20px;
            width: 255px;
            height: 41px;
            margin-top: 3px;
        }
        #regForm table,tr,td{
            border: none;
            background-color: rgb(245, 255, 235);
        }
        #regForm .lab{
            display: inline-block;
            width: 120px;
            text-align: right;
            line-height: 54px;
            font-size: 16px;
        }
        #regForm td{
            height: 50px;
        }
    </style>
{% endblock %}


{% block contentsMain %}
    <div style="width: 440px; padding: 40px 40px 60px 40px; margin: 120px auto; background-color: rgb(245, 255, 235); border: rgb(242, 252, 232) 1px solid; ">
        <div style="width: 186px; padding: 0 80px; margin: 0 auto; ">
            {% include "../include/relFlag.html" %}
        </div>
        <div style="text-align: center; margin: 10px 0 20px 0; font-size: 20px; ">新用户注册</div>
        <form id="regForm" action="{% url 'app-sys:register' %}" method="POST">
            {% csrf_token %}
            <table>
                <tr>
                    <td class="lab">{{ form.name.label_tag }}</td>
                    <td>{{ form.name }}</td>
                    <td>{{ form.name.errors }}</td>
                </tr>
                <tr>
                    <td class="lab">{{ form.mobile.label_tag }}</td>
                    <td>{{ form.mobile }}</td>
                    <td>{{ form.mobile.errors }}</td>
                </tr>
                <tr>
                    <td class="lab">{{ form.email.label_tag }}</td>
                    <td>{{ form.email }}</td>
                    <td>{{ form.email.errors }}</td>
                </tr>
                <tr>
                    <td class="lab">{{ form.loginPW.label_tag }}</td>
                    <td>{{ form.loginPW }}</td>
                    <td>{{ form.loginPW.errors }}</td>
                </tr>
                <tr>
                    <td class="lab">{{ form.reloginPW.label_tag }}</td>
                    <td>{{ form.reloginPW }}</td>
                    <td>{{ form.reloginPW.errors }}</td>
                </tr>
            </table>
            {% if info %}
                <p><label class="inputLabel"></label><label class="promptInfo">{{ info }}</label></p>
            {% endif %}
            <p><label class="inputLabel" for="i7"></label><input class="regOther" type="checkbox" name="greeitem" value="agreed"><span style="font-size: 14px; ">我已阅读并同意<a href="">《人情簿用户使用协议》</a></span></p>
            <p><label class="inputLabel"></label><input class="regButton" type="submit" value="提交" style="background-color: rgb(18, 150, 219); font-size: 18px; color: white; border: rgb(18, 150, 219) 1px solid; border-radius: 4px; "></p>
            <p><label class="inputLabel"></label><a style="font-size: 14px; " href="{% url 'app-sys:login' %}">已有用户登录</a></p>
        </form>
    </div>
{% endblock %}

humanRel/templates/sysmanager/set.html
{% extends "../extends/frameBaseModify.html" %}


{% block pageTitle %}设置{% endblock %}


{% block dataFree %}
    <form action="{% url 'app-sys:set' %}" method="POST">
        {% csrf_token %}
        <table>
            <tr>
                <td class="groupTitle" colspan="4">设置</td>
            </tr>
            <tr>
                <td class="col1">{{ form.id.label }}</td>
                <td class="col2">{{ form.id }}</td>
                <td class="col3">{{ form.id.errors }}</td>
                <td class="col4"><div class="subRemark"></div><div class="subRemark"></div></td>
            </tr>
            <tr>
                <td class="col1">{{ form.person.label }}</td>
                <td class="col2">{{ form.person }}</td>
                <td class="col3">{{ form.person.errors }}</td>
                <td class="col4"><div class="subRemark">选择当前登录账户对应的人员</div><div class="subRemark">设置后才能记录人情簿往来</div></td>
            </tr>
        </table>
        <p>
            <input class="inputBtn" type="submit" value="提交" style="margin-left: 196px; ">
            <input id="btnCancel" class="inputBtn" type="button" value="取消">
        </p>
    </form>
{% endblock %}


{% block scriptSub %}
    $("#btnCancel").click(function () {
        location.href = "{% url 'app-sys:index' %}"
    });
{% endblock %}