humanRel/apps/report/urls.py
from django.urls import path, re_path
from apps.report import views

urlpatterns = [
    re_path('repRelSum$', views.repRelSum, name="relSum"),
    re_path('repRelDetail$', views.repRelDetail, name="relDetail"),
    re_path('repRelForecast$', views.repRelForecast, name="relForecast"),
    re_path('repRelMap$', views.repRelMap, name="relMap"),
]

humanRel/humanRel/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sys/', include(("apps.sysmanager.urls", "app-sys"), namespace="app-sys")),
    path('base/', include(("apps.baseinfo.urls", "app-base"), namespace="app-base")),
    path('busi/', include(("apps.business.urls", "app-busi"), namespace="app-busi")),
    path('rep/', include(("apps.report.urls", "app-rep"), namespace="app-rep")),
]

humanRel/apps/report/views.py
from django.shortcuts import render
from django.db.models import Count, Sum
from apps.business.models import JoinRecord
from apps.baseinfo.models import Person
from utils.pages import Pages
from apps.sysmanager.views import auth
from datetime import datetime, date

# Create your views here.


@auth
def repRelSum(request, userID):
    dateFrom = request.GET.get("from", None)
    dateTo = request.GET.get("to", None)
    eventType = request.GET.get("eventType", "0")
    pageNo = request.GET.get("pageNo", "1")
    if not dateFrom or not dateTo:
        if not dateFrom:
            dateFrom = date.today()
        if not dateTo:
            dateTo = date.today()
        dataList = []
    else:
        dateFrom = datetime.strptime(dateFrom, "%Y-%m-%d")
        dateTo = datetime.strptime(dateTo, "%Y-%m-%d")
        if not eventType or eventType == "0":
            dataList = JoinRecord.objects.filter(user=userID, event__eventDate__gte=dateFrom, event__eventDate__lte=dateTo).values("event__family__name__name").annotate(timesRel=Count("event"), timesJoin=Count("id"), amtJoin=Sum("amtBook"), amtOther=Sum("amtOther"))
        else:
            dataList = JoinRecord.objects.filter(user=userID, event__eventDate__gte=dateFrom, event__eventDate__lte=dateTo, event__eventType=int(eventType)).values("event__family__name__name").annotate(timesRel=Count("event"), timesJoin=Count("id"), amtJoin=Sum("amtBook"), amtOther=Sum("amtOther"))
    cnt = request.COOKIES.get("reccnt_perpage")
    if not cnt:
        cnt = "10"
    page = Pages(len(dataList), int(cnt), "repRelSum?eventType=%s&pageNo=%s" % (eventType, pageNo))
    rep = render(request, "report/repRelSum.html", {"dataList": dataList[page.startRec:page.endRec], "from": dateFrom, "to": dateTo, "eventType": eventType, "pageNo": pageNo, "pagetag": page.pageStr, "recCnt": len(dataList)})
    rep.set_cookie("reccnt_perpage", cnt, path="/rep/")
    return rep


@auth
def repRelDetail(request, userID):
    dateFrom = request.GET.get("from", None)
    dateTo = request.GET.get("to", None)
    eventType = request.GET.get("eventType", "0")
    pageNo = request.GET.get("pageNo", "1")
    if not dateFrom or not dateTo:
        if not dateFrom:
            dateFrom = date.today()
        if not dateTo:
            dateTo = date.today()
        dataList = []
    else:
        dateFrom = datetime.strptime(dateFrom, "%Y-%m-%d")
        dateTo = datetime.strptime(dateTo, "%Y-%m-%d")
        if not eventType or eventType == "0":
            dataList = JoinRecord.objects.filter(user=userID, event__eventDate__gte=dateFrom, event__eventDate__lte=dateTo)
        else:
            dataList = JoinRecord.objects.filter(user=userID, event__eventDate__gte=dateFrom, event__eventDate__lte=dateTo, event__eventType=int(eventType))
    cnt = request.COOKIES.get("reccnt_perpage")
    if not cnt:
        cnt = "10"
    page = Pages(len(dataList), int(cnt), "repRelDetail?eventType=%s&pageNo=%s" % (eventType, pageNo))
    rep = render(request, "report/repRelDetail.html", {"dataList": dataList[page.startRec:page.endRec], "from": dateFrom, "to": dateTo, "eventType": eventType, "pageNO": pageNo, "pagetag": page.pageStr, "recCnt": len(dataList)})
    rep.set_cookie("reccnt_perpage", cnt, path="/rep/")
    return rep


@auth
def repRelForecast(request, userID):
    dateFrom = request.GET.get("from", None)
    dateTo = request.GET.get("to", None)
    eventType = request.GET.get("eventType", "0")
    pageNo = request.GET.get("pageNo", "1")
    if not dateFrom or not dateTo:
        if not dateFrom:
            dateFrom = date.today()
        if not dateTo:
            dateTo = date.today()
        dataList = []
    else:
        dateFrom = datetime.strptime(dateFrom, "%Y-%m-%d")
        dateTo = datetime.strptime(dateTo, "%Y-%m-%d")
        if not eventType or eventType == "0":
            dataList = []
        else:
            dataList = []
    cnt = request.COOKIES.get("reccnt_perpage")
    if not cnt:
        cnt = "10"
    page = Pages(len(dataList), int(cnt), "repRelForecast?eventType=%s&pageNo=%s" % (eventType, pageNo))
    rep = render(request, "report/repRelForecast.html", {"dataList": dataList[page.startRec:page.endRec], "from": dateFrom, "to": dateTo, "eventType": eventType, "pageNO": pageNo, "pagetag": page.pageStr, "recCnt": len(dataList)})
    rep.set_cookie("reccnt_perpage", cnt, path="/rep/")
    return rep


@auth
def repRelMap(request, userID):
    person1 = request.GET.get("person1", None)
    person2 = request.GET.get("person2", None)
    dataList = []
    personList = Person.objects.all()
    rep = render(request, "report/repRelMap.html", {"dataList": dataList, "person1": person1, "person2": person2, "personList": personList, "recCnt": len(dataList)})
    return rep

humanRel/templates/report/repRelDetail.html
{% extends "../extends/frameReport.html" %}


{% block pageTitle %}往来明细表{% endblock %}


{% block queryFields %}
    <div class="queryGroup">
        <div class="queryLabel">事件类型：</div>
        <select id="queryEventType" selectedValue="{{ eventType }}" class="queryItem">
            <option value="0" selected="selected">全部</option>
            <option value="1">结婚</option>
            <option value="2">生子</option>
            <option value="3">周岁</option>
            <option value="4">祝寿</option>
            <option value="5">考学</option>
            <option value="6">乔迁</option>
            <option value="7">身故</option>
            <option value="99">其他</option>
        </select>
    </div>
{% endblock %}


{% block dataGrid %}
    <table id="repData" pageNo="{{ pageNO }}">
        <thead>
        <tr>
            <th style="width: 50px; ">序号</th>
            <th style="width: 100px; ">日期</th>
            <th style="width: 140px; ">事件简称</th>
            <th style="width: 80px; ">家庭</th>
            <th style="width: 80px; ">当事人</th>
            <th style="width: 80px; ">事件类型</th>
            <th style="width: 80px; ">宴请类型</th>
            <th style="width: 80px; ">礼金</th>
            <th style="width: 80px; ">其他支出</th>
            <th style="width: 160px; ">备注</th>
        </tr>
        </thead>
        <tbody>
        {% for rec in dataList %}
            <tr>
                <td style="text-align: center; ">{{ forloop.counter }}</td>
                <td style="text-align: center; ">{{ rec.event.eventDate|date:"Y-m-d" }}</td>
                <td style="text-align: left; ">{{ rec.event.eventName }}</td>
                <td style="text-align: left; ">{{ rec.event.family }}</td>
                <td style="text-align: left; ">{{ rec.event.person }}</td>
                {% if rec.event.eventType == 1 %}
                    <td style="text-align: center; ">结婚</td>
                {% elif rec.event.eventType == 2 %}
                    <td style="text-align: center; ">生子</td>
                {% elif rec.event.eventType == 3 %}
                    <td style="text-align: center; ">周岁</td>
                {% elif rec.event.eventType == 4 %}
                    <td style="text-align: center; ">祝寿</td>
                {% elif rec.event.eventType == 5 %}
                    <td style="text-align: center; ">考学</td>
                {% elif rec.event.eventType == 6 %}
                    <td style="text-align: center; ">乔迁</td>
                {% elif rec.event.eventType == 7 %}
                    <td style="text-align: center; ">身故</td>
                {% else %}
                    <td style="text-align: center; ">其他</td>
                {% endif %}
                {% if rec.event.formType == 1 %}
                    <td style="text-align: center; ">隆重宴请</td>
                {% elif rec.event.formType == 2 %}
                    <td style="text-align: center; ">亲朋小聚</td>
                {% elif rec.event.formType == 3 %}
                    <td style="text-align: center; ">低调跳过</td>
                {% else %}
                    <td style="text-align: center; ">其他</td>
                {% endif %}
                <td style="text-align: right; ">{{ rec.amtBook }}</td>
                <td style="text-align: right; ">{{ rec.amtOther }}</td>
                <td style="text-align: left; ">{{ rec.remark }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}


{% block scriptSub %}
    $("#PAGE_reccnt_perpage_select").change(function () {
        $.cookie("reccnt_perpage", $(this).val(), {path: "/rep/"});
        sHref = "{% url 'app-rep:relDetail' %}";
        sHref = sHref + "?from=" + $("#dateFrom").val();
        sHref = sHref + "&to=" + $("#dateTo").val();
        sHref = sHref + "&eventType=" + $("#queryEventType").val();
        sHref = sHref + "&pageNo=1";
        location.href = sHref;
    });
    $("#queryEventType").children().each(function () {
        if ($(this).val() == $("#queryEventType").attr("selectedValue")) {
            $(this).attr("selected", "selected");
        }
    });
    $("#btnQuery").click(function () {
        sHref = "{% url 'app-rep:relDetail' %}"
        sHref = sHref + "?from=" + $("#dateFrom").val();
        sHref = sHref + "&to=" + $("#dateTo").val();
        sHref = sHref + "&eventType=" + $("#queryEventType").val();
        sHref = sHref + "&pageNo=" + $("#repData").attr("pageNo");
        location.href = sHref;
    });
{% endblock %}

humanRel/templates/report/repRelForecast.html
{% extends "../extends/frameReport.html" %}


{% block pageTitle %}往来预测报表{% endblock %}


{% block queryFields %}
    <div class="queryGroup">
        <div class="queryLabel">事件类型：</div>
        <select id="queryEventType" selectedValue="{{ eventType }}" class="queryItem">
            <option value="0" selected="selected">全部</option>
            <option value="1">结婚</option>
            <option value="2">生子</option>
            <option value="3">周岁</option>
            <option value="4">祝寿</option>
            <option value="5">考学</option>
            <option value="6">乔迁</option>
            <option value="7">身故</option>
            <option value="99">其他</option>
        </select>
    </div>
{% endblock %}


{% block dataGrid %}
    <table id="repData" pageNo="{{ pageNO }}">
        <thead>
        <tr>
            <th style="width: 50px; ">序号</th>
            <th style="width: 120px; ">家庭</th>
            <th style="width: 120px; ">当事人</th>
            <th style="width: 120px; ">预测日期</th>
            <th style="width: 120px; ">事件类型</th>
            <th style="width: 410px; ">预测依据</th>
        </tr>
        </thead>
        <tbody>
        {% for rec in dataList %}
            <tr>
                <td style="text-align: center; "></td>
                <td style="text-align: left; "></td>
                <td style="text-align: right; "></td>
                <td style="text-align: right; "></td>
                <td style="text-align: right; "></td>
                <td style="text-align: right; "></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}


{% block scriptSub %}
    $("#PAGE_reccnt_perpage_select").change(function () {
        $.cookie("reccnt_perpage", $(this).val(), {path: "/rep/"});
        sHref = "{% url 'app-rep:relForecast' %}";
        sHref = sHref + "?from=" + $("#dateFrom").val();
        sHref = sHref + "&to=" + $("#dateTo").val();
        sHref = sHref + "&eventType=" + $("#queryEventType").val();
        sHref = sHref + "&pageNo=1";
        location.href = sHref;
    });
    $("#queryEventType").children().each(function () {
        if ($(this).val() == $("#queryEventType").attr("selectedValue")) {
            $(this).attr("selected", "selected");
        }
    });
    $("#btnQuery").click(function () {
        sHref = "{% url 'app-rep:relForecast' %}";
        sHref = sHref + "?from=" + $("#dateFrom").val();
        sHref = sHref + "&to=" + $("#dateTo").val();
        sHref = sHref + "&eventType=" + $("#queryEventType").val();
        sHref = sHref + "&pageNo=" + $("#repData").attr("pageNo");
        location.href = sHref;
    });
{% endblock %}

humanRel/templates/report/repRelMap.html
{% extends "../extends/frameReport.html" %}


{% block pageTitle %}人物关系图谱{% endblock %}


{% block queryCondition %}
    <div class="queryGroup">
        <div class="queryLabel">人员1：</div>
        <select id="queryPerson1" selectedValue="{{ person1 }}" class="queryItem">
            <option value="" selected="selected">（未选择）</option>
            {% for person in personList %}
                <option value="{{ person.id }}">{{ person.name }}</option>
            {% endfor %}
        </select>
    </div>
    <div class="queryGroup">
        <div class="queryLabel">人员2：</div>
        <select id="queryPerson2" selectedValue="{{ person2 }}" class="queryItem">
            <option value="" selected="selected">（未选择）</option>
            {% for person in personList %}
                <option value="{{ person.id }}">{{ person.name }}</option>
            {% endfor %}
        </select>
    </div>
{% endblock %}


{% block dataGrid %}
    <table id="repData" pageNo="{{ pageNo }}">
        <thead>
        <tr>
            <th style="width: 50px; ">序号</th>
            <th style="width: 120px; ">家庭</th>
            <th style="width: 120px; ">人员</th>
            <th style="width: 160px; ">关系</th>
            <th style="width: 120px; ">目标人员</th>
            <th style="width: 370px; "></th>
        </tr>
        </thead>
        <tbody>
        {% for rec in dataList %}
            <tr>
                <td style="text-align: center; "></td>
                <td style="text-align: left; "></td>
                <td style="text-align: left; "></td>
                <td style="text-align: left; "></td>
                <td style="text-align: left; "></td>
                <td></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}


{% block scriptSub %}
    $("#PAGE_reccnt_perpage_select").change(function () {
        $.cookie("reccnt_perpage", $(this).val(), {path: "/rep/"});
        sHref = "{% url 'app-rep:relMap' %}";
        sHref = sHref + "?person1=" + $("#queryPerson1").val();
        sHref = sHref + "&person2=" + $("#queryPerson2").val();
        location.href = sHref;
    });
    $("#queryEventType").children().each(function () {
        if ($(this).val() == $("#queryEventType").attr("selectedValue")) {
            $(this).attr("selected", "selected");
        }
    });
    $("#btnQuery").click(function () {
        sHref = "{% url 'app-rep:relMap' %}";
        sHref = sHref + "?person1=" + $("#queryPerson1").val();
        sHref = sHref + "&person2=" + $("#queryPerson2").val();
        location.href = sHref;
    });
{% endblock %}

humanRel/templates/report/repRelSum.html
{% extends "../extends/frameReport.html" %}


{% block pageTitle %}往来汇总表{% endblock %}


{% block queryFields %}
    <div class="queryGroup">
        <div class="queryLabel">事件类型：</div>
        <select id="queryEventType" selectedValue="{{ eventType }}" class="queryItem">
            <option value="0" selected="selected">全部</option>
            <option value="1">结婚</option>
            <option value="2">生子</option>
            <option value="3">周岁</option>
            <option value="4">祝寿</option>
            <option value="5">考学</option>
            <option value="6">乔迁</option>
            <option value="7">身故</option>
            <option value="99">其他</option>
        </select>
    </div>
{% endblock %}


{% block dataGrid %}
    <table id="repData" pageNo="{{ pageNo }}">
        <thead>
        <tr>
            <th style="width: 50px; ">序号</th>
            <th style="width: 120px; ">家庭</th>
            <th style="width: 120px; ">宴请次数</th>
            <th style="width: 120px; ">随礼次数</th>
            <th style="width: 120px; ">随礼金额</th>
            <th style="width: 120px; ">其他金额</th>
            <th style="width: 290px; "></th>
        </tr>
        </thead>
        <tbody>
        {% for rec in dataList %}
            <tr>
                <td style="text-align: center; ">{{ forloop.counter }}</td>
                <td style="text-align: left; ">{{ rec.event__family__name__name }}</td>
                <td style="text-align: right; ">{{ rec.timesRel }}</td>
                <td style="text-align: right; ">{{ rec.timesJoin }}</td>
                <td style="text-align: right; ">{{ rec.amtJoin }}</td>
                <td style="text-align: right; ">{{ rec.amtOther }}</td>
                <td></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}


{% block scriptSub %}
    $("#PAGE_reccnt_perpage_select").change(function () {
        $.cookie("reccnt_perpage", $(this).val(), {path: "/rep/"});
        sHref = "{% url 'app-rep:relSum' %}";
        sHref = sHref + "?from=" + $("#dateFrom").val();
        sHref = sHref + "&to=" + $("#dateTo").val();
        sHref = sHref + "&eventType=" + $("#queryEventType").val();
        sHref = sHref + "&pageNo=1";
        location.href = sHref;
    });
    $("#queryEventType").children().each(function () {
        if ($(this).val() == $("#queryEventType").attr("selectedValue")) {
            $(this).attr("selected", "selected");
        }
    });
    $("#btnQuery").click(function () {
        sHref = "{% url 'app-rep:relSum' %}";
        sHref = sHref + "?from=" + $("#dateFrom").val();
        sHref = sHref + "&to=" + $("#dateTo").val();
        sHref = sHref + "&eventType=" + $("#queryEventType").val();
        sHref = sHref + "&pageNo=" + $("#repData").attr("pageNo");
        location.href = sHref;
    });
{% endblock %}